<a href="https://colab.research.google.com/github/mlindsey19/evol-comp-two/blob/master/EvolComp2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import random
import numpy as np

N = 10 # must be even for crossover
RUNS = 30
LOCI = 3
LCBD = (-1.0, 5.0) #loci bounds
#print format -> #.###
float_formatter = lambda x: "%.8f" % x
np.set_printoptions( formatter = { 'float_kind' : float_formatter } )

gen = np.random.uniform( LCBD[ 0 ], LCBD[ 1 ], ( N, LOCI ) )


In [0]:
pen = 2
penFlag = 1

def fitness( individual ):
  fit = 0
  for x in individual:
    fit +=  pen * x**2 if ( penFlag and ( x > 5.0 or x < -1.0 ) ) else x**2
  return fit

def fitVector(g, n):
  fit = np.empty(n)
  for i in range(n):
    fit[ i ] = fitness( g[ i ] )
  return fit


def sortFit( g, n = N ):
  temp = np.c_[ g, fitVector( g, n ) ]
  return temp[ temp[ : , 3 ].argsort() ]


In [0]:
Pc = 0.8
alpha = 0.7
shuffFlag = 0

def crossover(  ):
  if ( shuffFlag ):
    np.random.shuffle( gen )
  for i in range( N // 2 ):
    if ( np.random.uniform( 0, 1 ) < Pc ):
      j = 2 * i
      gen[ j ][ 0 ], gen[ j + 1 ][ 0 ] = gen[ j + 1 ][ 0 ],  gen[ j ][ 0 ]
#  return gen

def arithmeticCrossover(  ):
  if ( shuffFlag ):
    np.random.shuffle( gen )
  for i in range( N // 2 ):
    if ( np.random.uniform( 0, 1 ) < Pc ):
      j = 2 * i
      x = gen[ j + 1 ][ 0 ] + gen[ j ][ 0 ]
      gen[ j ][ 0 ], gen[ j + 1 ][ 0 ] = ( 1 - alpha ) * x, alpha * x
  #    return gen

def arithmeticCrossPerLoci(  ):
  if ( shuffFlag ):
    np.random.shuffle( gen )
  for i in range( N // 2 ):
    for h in range( 3 ):        
      j = 2 * i
      if ( np.random.uniform( 0, 1 ) < Pc ):
        x = gen[ j + 1 ][ h ] + gen[ j ][ h ]
        gen[ j ][ h ], gen[ j + 1 ][ h ] = ( 1 - alpha ) * x, alpha * x
 # return gen
    
  
 

***mr*** mutation range
***ub*** upper bound

The upper bound is calculated so that numbers selected at random fall in an appropriate 
range of mutation ***P*** % of the time 

In [0]:
Pm = 0.1
mr = 0.75

def mut():
  mtmt = np.empty( ( N, LOCI) )
  ub = ( 2 * mr / Pm ) - mr
  for i in range ( N ):
    for j in range(LOCI):
      m = np.random.uniform( (0 - mr), ub )
      if ( m < mr ):
        mtmt[i][j] = m
      else:
        mtmt[i][j] = 0  
  return mtmt

def gausIndi():
  mtmt = np.empty( ( N, LOCI) )

  for i in range ( N ):
    sd = np.std(gen[i])
    for j in range(LOCI):
      m = np.random.uniform( 0 , 1 )
      if ( m < Pm ):
        mtmt[i][j] = np.random.normal(0, sd)
      else:
        mtmt[i][j] = 0   
  return mtmt

def gausPop():
  sd = np.std(gen)
  mtmt = np.random.normal( 0.0, sd, ( N, LOCI) )

  for i in range ( N ):
    for j in range(LOCI):
      m = np.random.uniform( 0 , 1 )
      if ( m > Pm ):
            mtmt[i][j] = 0  
  return mtmt

def mutation(  ):
  global gen
  gen = gen + mut()

def gpmutation(  ):
  global gen
  gen = gen + gausPop()
def gimutation(  ):
  global gen
  gen = gen + gausIndi()


def mutationWithClamp(  ):
  global gen
  ngen = gen + mut()
  for rw in range( N ):
    for cl in range( LOCI ):  
        ngen[rw][cl] = ngen[rw][cl] if ( ngen[rw][cl] > -1 ) else -1
        ngen[rw][cl] = ngen[rw][cl] if ( ngen[rw][cl] < 5 ) else 5
  gen = ngen

  
print( gen )
grmutation()

print( gen )



In [0]:
Psbt = 0.4

def selectionBT(  ):
  global gen
  ngen = np.empty( ( N, LOCI) )
  for i in range(N):
    x = gen[ random.randint( 0, N - 1 ) ]
    y = gen[ random.randint( 0, N - 1 ) ]
    #print( x , y)
    if( fitness( x ) > fitness( y ) ):
      x = y
    ngen[ i ] = x
  gen = ngen

selectionBT()

print( gen )

In [0]:
min = .5
max = 2 - min
Plr = lambda r:( min + ( r - 1 ) / ( N - 1 ) * ( max - min ) ) / N
PlrMap = np.array( [ Plr(x) for x in range( 1, 11 ) ] ) 
pmap =np.empty(N)
for i in range(N):
  if (i == 0):
    pmap[ i ] = PlrMap[ i ]
  else:
    pmap[ i ] = PlrMap[ i ] + pmap[ i - 1 ]


def selectionLR(  ):
  global gen
  ngen = np.empty( (N, LOCI) )
  temp = sortFit( gen )
  for i in range( N ):
    s = np.random.uniform( 0, 1 )
    for idx,c in enumerate(pmap):
      if( s <= c ):
        #print(s, c , 9 - idx)
        ngen[ i ] = temp[ 9-idx, : 3 ] 
        break
  gen = ngen

en = 2  # number of best fit guarantee propogate  

def selectionEliteLR(  ):
  global gen
  ngen = np.empty( (N, LOCI) )
  temp = sortFit( gen )
  for i in range( en ):
    ngen[ i ] = temp[ i, : 3]
  for i in range( en, N ):
    s = np.random.uniform( 0, 1 )
    for idx,c in enumerate(pmap):
      if( s <= c ):
        #print(s, c , 9 - idx)
        ngen[ i ] = temp[ 9-idx, : 3 ] 
        break
  gen = ngen

selectionLR()
print(gen)
selectionEliteLR()

print( gen )

In [0]:
tn = 8 # number to keep

firstRunFlag = 1
if ( firstRunFlag ):
  firstRunFlag = 0
  prevgen = np.random.uniform( LCBD[ 0 ], LCBD[ 1 ], ( N, LOCI ) )
  
def selectionTrunc(  ):
  global gen
  ngen = np.empty( ( N, LOCI ) )
  temp = sortFit( gen )
  for i in range( tn ):
    ngen[ i ] = temp[ i, : 3 ]
  for i in range ( tn, N ):
    ngen [ i ] = np.random.uniform( LCBD[ 0 ], LCBD[ 1 ], ( 1, LOCI ) )
  gen = ngen

def selectionFibTrunc(  ):
  global gen
  ngen = np.empty( ( N, LOCI ) )
  global prevgen
  temp = gen
  union = np.append(gen, prevgen, axis = 0)
  union = sortFit(union, n=(2 * N) )
  prevgen = temp
  for i in range( tn ):
    ngen[ i ] = union[ i, : 3 ]
  for i in range ( tn, N ):
    ngen [ i ] = np.random.uniform( LCBD[ 0 ], LCBD[ 1 ], ( 1, LOCI ) )
  gen = ngen

selectionFibTrunc()
print(gen)


In [0]:
for i in range(50):
  mutation()
  mutationWithClamp()
  arithmeticCrossPerLoci()
  arithmeticCrossover()
  arithmeticCrossPerLoci()
  crossover()
  selectionBT() 
  selectionTrunc() 
  selectionFibTrunc()
  selectionLR()
  selectionEliteLR()
print (gen)



In [50]:


mutList = [ gimutation, mutation, gpmutation]
crossList = [ arithmeticCrossover, arithmeticCrossPerLoci, crossover ]
selList = [ selectionBT, selectionTrunc, selectionFibTrunc, selectionLR, selectionEliteLR ]
avg = np.empty((5,3,3))
best = np.empty((5,3,3))
stdv = np.empty((5,3,3))
def evol():
  global gen
  global avg
  global best 
  global stdv
  bst = 0.0
  avgVector = np.empty(30)
  for s, sel in enumerate( selList ):
    for c, cross in enumerate( crossList ):
      for m, mut in enumerate( mutList ):
          for i in range( 30 ):
            gen = np.random.uniform( LCBD[ 0 ], LCBD[ 1 ], ( N, LOCI ) )
            for _ in range( 50 ):
              sel()
              cross()
              mut()
            bst = np.amin(fitVector(gen, N))
            avgVector[ i ] = np.mean(fitVector(gen, N))
          best[s][c][m] = bst if (bst < best[s][c][m] ) else best[s][c][m]
          avg[s][c][m] = np.mean(avgVector)
          stdv[s][c][m] = np.std(avgVector)



evol()

print( avg )
print( best )
print( stdv )

[[[0.01097184 0.08473523 0.00259881]
  [0.00000000 0.07259170 0.00000000]
  [0.00683067 0.09526067 0.02239833]]

 [[5.77683828 6.32933542 8.42449454]
  [4.35025597 6.39636644 6.77835535]
  [5.95579596 6.14281717 9.49101621]]

 [[4.87518556 4.08790154 5.62738247]
  [4.70178776 4.56076952 5.74105594]
  [5.69797635 4.86973298 4.71404009]]

 [[0.06366778 0.34156902 0.07365137]
  [0.00000749 0.09701633 0.00010271]
  [0.10290342 0.64204747 0.10749099]]

 [[0.00018437 0.10371572 0.00046216]
  [0.00000000 0.08300091 0.00000000]
  [0.00039049 0.11953012 0.00111594]]]
[[[0.00011629 0.00822868 0.00001257]
  [0.00000000 0.00003035 0.00000000]
  [0.00000188 0.00051981 0.00030812]]

 [[0.17467024 0.23862080 0.38496342]
  [0.00099137 0.00119967 0.00795302]
  [0.02186425 0.44745475 0.76700099]]

 [[0.00000000 0.00000000 0.00000000]
  [0.00000000 0.00000000 0.00000000]
  [0.00000000 0.00000000 0.00000000]]

 [[0.00012623 0.06963906 0.00013907]
  [0.00000232 0.01039175 0.00000011]
  [0.02206149 0.002425